CLASS zrap110_travel_event_handl_022 DEFINITION
  PUBLIC
  FINAL      FOR EVENTS OF ZRAP110_R_TRAVELTP_022
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap110_travel_event_handl_022 IMPLEMENTATION.
ENDCLASS.
